# Generated by Django 4.1 on 2022-10-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_alter_customusermodel_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customusermodel',
            table='RegisteredUser',
        ),
    ]
