# Generated by Django 4.1 on 2022-10-07 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_alter_customusermodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.EmailValidator(), django.core.validators.MaxLengthValidator(254, 'Email cannot be more than 254 characters.')]),
        ),
        migrations.AlterModelTable(
            name='customusermodel',
            table='registered_users',
        ),
    ]
