# Generated by Django 4.1 on 2022-10-10 11:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing_page', '0004_alter_customusermodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Must contain only standard alphabetic characters.', regex='/^[a-z]+$/'), django.core.validators.MaxLengthValidator(50)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Must contain only standard alphabetic characters.', regex='/^[a-z]+$/'), django.core.validators.MaxLengthValidator(50)])),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('Bio', models.TextField(default='', max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
            ],
        ),
    ]
