# Generated by Django 4.1 on 2022-10-10 23:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='home.userprofile')),
                ('address_line_one', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(flags=[re.RegexFlag['IGNORECASE'], re.RegexFlag['MULTILINE']], message='Must contain only standard alphabetic characters and numbers.', regex='/[a-z0-9]+|([a-z0-9]?<=)\\s(?=[a-z0-9])/'), django.core.validators.MaxLengthValidator(100)], verbose_name='Address line 1')),
                ('city_or_town', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(flags=[re.RegexFlag['IGNORECASE']], message='Must contain only standard alphabetic characters.', regex='/^[a-z]+$/'), django.core.validators.MaxLengthValidator(50)], verbose_name='City/Town')),
                ('county', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(flags=[re.RegexFlag['IGNORECASE']], message='Must contain only standard alphabetic characters.', regex='/^[a-z]+$/'), django.core.validators.MaxLengthValidator(50)], verbose_name='County')),
                ('postcode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Must be a valid postcode format.', regex='/^(([gG][iI][rR] {0,}0[aA]{2})|((([a-pr-uwyzA-PR-UWYZ][a-hk-yA-HK-Y]?[0-9][0-9]?)|(([a-pr-uwyzA-PR-UWYZ][0-9][a-hjkstuwA-HJKSTUW])|([a-pr-uwyzA-PR-UWYZ][a-hk-yA-HK-Y][0-9][abehmnprv-yABEHMNPRV-Y]))) {0,}[0-9][abd-hjlnp-uw-zABD-HJLNP-UW-Z]{2}))$/'), django.core.validators.MaxLengthValidator(10)], verbose_name='Postcode')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.DecimalValidator(8, 4)])),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.DecimalValidator(8, 4)])),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Bio',
            new_name='bio',
        ),
    ]
