# Generated by Django 4.1 on 2022-10-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_useraddress_address_line_one_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'User Address', 'verbose_name_plural': 'User Addresses'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
