# Generated by Django 4.1 on 2022-10-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_activities', '0004_alter_eventsactivities_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsactivities',
            options={'verbose_name': 'Events and Activities', 'verbose_name_plural': 'Events and Activities'},
        ),
    ]
