# Generated by Django 4.2 on 2023-04-24 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_and_activities', '0014_alter_eventsactivities_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('In', 'Interested'), ('Att', 'Attending'), ('Attd', 'Attended')], default='In', max_length=4, verbose_name='engagement status')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='events_and_activities.eventsactivities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='engaged user')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.AddField(
            model_name='eventsactivities',
            name='attendees',
            field=models.ManyToManyField(related_name='event', through='events_and_activities.Engagement', to=settings.AUTH_USER_MODEL),
        ),
    ]
