# Generated by Django 4.2 on 2023-05-10 21:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_activities', '0015_engagement_eventsactivities_attendees'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='engagement',
            managers=[
                ('user_status', django.db.models.manager.Manager()),
            ],
        ),
    ]
